#!/usr/bin/env python3
"""Render the E CHABOT wordmark to a monochrome ZPL ^GFA graphic.

This produces a working type-based wordmark so the tag prints today.
To use Brian's official EPS instead, run tools/image_to_zpl.py on the EPS
and replace the LOGO_ZPL string in src/assets/logoZpl.js.
"""
from PIL import Image, ImageDraw, ImageFont

TEXT = "E CHABOT"
TARGET_H = 28           # dots tall @300dpi (~0.093")
FONT = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

def render():
    font = ImageFont.truetype(FONT, TARGET_H)
    # measure
    tmp = Image.new("L", (10, 10), 255)
    d = ImageDraw.Draw(tmp)
    bbox = d.textbbox((0, 0), TEXT, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    img = Image.new("L", (w + 4, h + 4), 255)
    d = ImageDraw.Draw(img)
    d.text((2 - bbox[0], 2 - bbox[1]), TEXT, font=font, fill=0)
    # 1-bit: black ink = 1
    MAX_W = 110  # keep inside the 131-dot face with margin
    if img.width > MAX_W:
        nh = max(1, round(img.height * MAX_W / img.width))
        img = img.resize((MAX_W, nh), Image.LANCZOS)
    bw = img.point(lambda px: 0 if px > 128 else 1, mode="1")
    return bw

def to_gfa(img):
    w, h = img.size
    bytes_per_row = (w + 7) // 8
    total = bytes_per_row * h
    px = img.load()
    rows = []
    for y in range(h):
        byte = 0
        bits = 0
        rowhex = []
        for x in range(w):
            byte = (byte << 1) | (1 if px[x, y] else 0)
            bits += 1
            if bits == 8:
                rowhex.append("%02X" % byte); byte = 0; bits = 0
        if bits:
            byte = byte << (8 - bits)
            rowhex.append("%02X" % byte)
        rows.append("".join(rowhex))
    hexdata = "".join(rows)
    gfa = "^GFA,%d,%d,%d,%s" % (total, total, bytes_per_row, hexdata)
    return gfa, w, h, total

if __name__ == "__main__":
    img = render()
    gfa, w, h, total = to_gfa(img)
    js = (
        "// src/assets/logoZpl.js\n"
        "// Monochrome E CHABOT wordmark as a ZPL ^GFA graphic (single color, black).\n"
        "// Generated by tools/gen_logo.py from rendered type (Liberation Sans Bold).\n"
        "// To swap in Brian's official EPS: run tools/image_to_zpl.py <logo> and\n"
        "// replace the string below. Dimensions: %dx%d dots, %d bytes.\n"
        "export const LOGO_ZPL = '%s';\n"
        "export const LOGO_DIMS = { width: %d, height: %d };\n"
    ) % (w, h, total, gfa, w, h)
    with open("src/assets/logoZpl.js", "w") as f:
        f.write(js)
    print("logo: %dx%d dots, %d bytes, hexlen=%d" % (w, h, total, len(gfa)))
