#!/usr/bin/env python3
"""Convert a logo image (EPS / PNG / SVG-rasterized) to a monochrome ZPL ^GFA
graphic and write it as src/assets/logoZpl.js.

Usage:
    python tools/image_to_zpl.py path/to/E-CHABOT.eps [--width 110] [--threshold 128]

Notes:
  - EPS input requires Ghostscript installed (PIL shells out to it).
  - The tag is single-color (black). The wordmark prints black; any gold in the
    art does not carry to thermal. Start from clean vector art for a crisp edge.
  - Output width defaults to 110 dots to sit inside the 0.4375" (131-dot) face.
"""
import argparse
from PIL import Image


def to_gfa(img):
    w, h = img.size
    bpr = (w + 7) // 8
    total = bpr * h
    px = img.load()
    out = []
    for y in range(h):
        byte = 0
        bits = 0
        for x in range(w):
            byte = (byte << 1) | (1 if px[x, y] else 0)
            bits += 1
            if bits == 8:
                out.append("%02X" % byte)
                byte = 0
                bits = 0
        if bits:
            out.append("%02X" % (byte << (8 - bits)))
    return "^GFA,%d,%d,%d,%s" % (total, total, bpr, "".join(out)), w, h, total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image")
    ap.add_argument("--width", type=int, default=110, help="target width in dots")
    ap.add_argument("--threshold", type=int, default=128, help="0-255 ink threshold")
    ap.add_argument("--out", default="src/assets/logoZpl.js")
    args = ap.parse_args()

    img = Image.open(args.image)
    # Flatten transparency onto white, then grayscale.
    if img.mode in ("RGBA", "LA") or (img.mode == "P" and "transparency" in img.info):
        bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
        img = Image.alpha_composite(bg, img.convert("RGBA"))
    img = img.convert("L")

    if args.width and img.width > args.width:
        nh = max(1, round(img.height * args.width / img.width))
        img = img.resize((args.width, nh), Image.LANCZOS)

    # 1-bit: ink (dark) -> 1
    bw = img.point(lambda p: 0 if p > args.threshold else 1, mode="1")
    gfa, w, h, total = to_gfa(bw)

    js = (
        "// src/assets/logoZpl.js\n"
        "// Monochrome E CHABOT wordmark as a ZPL ^GFA graphic (single color, black).\n"
        "// Generated by tools/image_to_zpl.py from %s. Dimensions: %dx%d dots, %d bytes.\n"
        "export const LOGO_ZPL = '%s';\n"
        "export const LOGO_DIMS = { width: %d, height: %d };\n"
    ) % (args.image, w, h, total, gfa, w, h)
    with open(args.out, "w") as f:
        f.write(js)
    print("wrote %s (%dx%d dots, %d bytes)" % (args.out, w, h, total))


if __name__ == "__main__":
    main()
